###  Balanceofpayments2017q3, TabC

In [1]:
from databaker.framework import *

In [2]:
import pandas as pd

In [3]:
inputFile = 'balanceofpayments2017q3.xls'

In [4]:
tab = loadxlstabs(inputFile)

Loading balanceofpayments2017q3.xls which has size 309248 bytes
Table names: ['Index', 'Records', 'Table A', 'Table B', 'Table C', 'Table D', 'Table E', 'Table F', 'Table G', 'Table H', 'Table I', 'Table J', 'Table K', 'Table R1', 'Table R2', 'Table R3']

In [5]:
tab = tab[4]

In [6]:
savepreviewhtml(tab)

In [7]:
observations = tab.excel_ref('D10').expand(DOWN).expand(RIGHT).is_not_blank()

In [8]:
savepreviewhtml(observations)

In [9]:
Code = tab.excel_ref('C10').expand(DOWN).is_not_blank()

In [10]:
savepreviewhtml(Code)

In [11]:
Year = tab.excel_ref('D4').expand(RIGHT).is_not_blank()
Quarter = tab.excel_ref('D5').expand(RIGHT)

In [12]:
savepreviewhtml(Year)

In [13]:
savepreviewhtml(Quarter)

In [14]:
Region = tab.excel_ref('B').expand(DOWN).by_index([7,42]) - tab.excel_ref('B77').expand(DOWN)

In [15]:
savepreviewhtml(Region)

In [16]:
Transactions = tab.excel_ref('B').expand(DOWN).by_index([9,20,31,44,55,66])

In [17]:
savepreviewhtml(Transactions)

In [19]:
Services = tab.excel_ref('B').is_not_blank().is_not_whitespace() - Region - Transactions

In [20]:
Services = Services - tab.excel_ref('B77').expand(DOWN) -tab.excel_ref('B2').expand(UP)

In [21]:
savepreviewhtml(Services)

In [22]:
Currency = tab.excel_ref('N3')

In [23]:
savepreviewhtml(Currency)

In [26]:
Dimensions = [
            HDimConst('GEOG', 'K02000001'),
            HDim(Year,'Year',DIRECTLY,ABOVE),
            HDim(Quarter,'Quarter',DIRECTLY,ABOVE),
            HDim(Code,'Code Identifier',DIRECTLY,LEFT),
            HDimConst('Currency', 'GBP(millions)'),            
            HDim(Services,'Services',CLOSEST, ABOVE),
            HDim(Transactions,'Type of Transactions',CLOSEST,ABOVE),
            HDim(Region,'Transactions Region',CLOSEST,ABOVE)
            
    
]

In [27]:
c1 = ConversionSegment(observations, Dimensions, processTIMEUNIT=True)
savepreviewhtml(c1)

In [28]:
new_table = c1.topandas()
new_table

,OBS,GEOG,Year,Quarter,Code,Currency,Services,Type of Transactions,Transactions Region
0,138865.0,K02000001,2015.0,,L87S,GBP(millions),Exports of goods,Credits,"Transactions with the European Union 1,2,3,4"
1,145471.0,K02000001,2016.0,,L87S,GBP(millions),Exports of goods,Credits,"Transactions with the European Union 1,2,3,4"
2,34844.0,K02000001,2015.0,Q3,L87S,GBP(millions),Exports of goods,Credits,"Transactions with the European Union 1,2,3,4"
3,34035.0,K02000001,2015.0,Q4,L87S,GBP(millions),Exports of goods,Credits,"Transactions with the European Union 1,2,3,4"
4,33205.0,K02000001,2016.0,Q1,L87S,GBP(millions),Exports of goods,Credits,"Transactions with the European Union 1,2,3,4"
5,35731.0,K02000001,2016.0,Q2,L87S,GBP(millions),Exports of goods,Credits,"Transactions with the European Union 1,2,3,4"
6,37400.0,K02000001,2016.0,Q3,L87S,GBP(millions),Exports of goods,Credits,"Transactions with the European Union 1,2,3,4"
7,39135.0,K02000001,2016.0,Q4,L87S,GBP(millions),Exports of goods,Credits,"Transactions with the European Union 1,2,3,4"
8,40114.0,K02000001,2017.0,Q1,L87S,GBP(millions),Exports of goods,Credits,"Transactions with the European Union 1,2,3,4"
9,41518.0,K02000001,2017.0,Q2,L87S,GBP(millions),Exports of goods,Credits,"Transactions with the European Union 1,2,3,4"
10,43231.0,K02000001,2017.0,Q3,L87S,GBP(millions),Exports of goods,Credits,"Transactions with the European Union 1,2,3,4"
11,90486.0,K02000001,2015.0,,L854,GBP(millions),Exports of services,Credits,"Transactions with the European Union 1,2,3,4"
12,95274.0,K02000001,2016.0,,L854,GBP(millions),Exports of services,Credits,"Transactions with the European Union 1,2,3,4"
13,22759.0,K02000001,2015.0,Q3,L854,GBP(millions),Exports of services,Credits,"Transactions with the European Union 1,2,3,4"
14,22300.0,K02000001,2015.0,Q4,L854,GBP(millions),Exports of services,Credits,"Transactions with the European Union 1,2,3,4"
15,22793.0,K02000001,2016.0,Q1,L854,GBP(millions),Exports of services,Credits,"Transactions with the European Union 1,2,3,4"
16,22918.0,K02000001,2016.0,Q2,L854,GBP(millions),Exports of services,Credits,"Transactions with the European Union 1,2,3,4"
17,24033.0,K02000001,2016.0,Q3,L854,GBP(millions),Exports of services,Credits,"Transactions with the European Union 1,2,3,4"
18,25530.0,K02000001,2016.0,Q4,L854,GBP(millions),Exports of services,Credits,"Transactions with the European Union 1,2,3,4"
19,25943.0,K02000001,2017.0,Q1,L854,GBP(millions),Exports of services,Credits,"Transactions with the European Union 1,2,3,4"
20,26951.0,K02000001,2017.0,Q2,L854,GBP(millions),Exports of services,Credits,"Transactions with the European Union 1,2,3,4"
21,27108.0,K02000001,2017.0,Q3,L854,GBP(millions),Exports of services,Credits,"Transactions with the European Union 1,2,3,4"
22,229351.0,K02000001,2015.0,,L84Y,GBP(millions),Total exports of goods and services,Credits,"Transactions with the European Union 1,2,3,4"
23,240745.0,K02000001,2016.0,,L84Y,GBP(millions),Total exports of goods and services,Credits,"Transactions with the European Union 1,2,3,4"
24,57603.0,K02000001,2015.0,Q3,L84Y,GBP(millions),Total exports of goods and services,Credits,"Transactions with the European Union 1,2,3,4"
25,56335.0,K02000001,2015.0,Q4,L84Y,GBP(millions),Total exports of goods and services,Credits,"Transactions with the European Union 1,2,3,4"
26,55998.0,K02000001,2016.0,Q1,L84Y,GBP(millions),Total exports of goods and services,Credits,"Transactions with the European Union 1,2,3,4"
27,58649.0,K02000001,2016.0,Q2,L84Y,GBP(millions),Total exports of goods and services,Credits,"Transactions with the European Union 1,2,3,4"
28,61433.0,K02000001,2016.0,Q3,L84Y,GBP(millions),Total exports of goods and services,Credits,"Transactions with the European Union 1,2,3,4"
29,64665.0,K02000001,2016.0,Q4,L84Y,GBP(millions),Total exports of goods and services,Credits,"Transactions with the European Union 1,2,3,4"
...,...,...,...,...,...,...,...,...,...
366,-11112.0,K02000001,2015.0,Q4,L87H,GBP(millions),Primary income,Balances,"Transactions with non-EU countries 4,5,6"
367,-6822.0,K02000001,2016.0,Q1,L87H,GBP(millions),Primary income,Balances,"Transactions with non-EU countries 4,5,6"
368,-7158.0,K02000001,2016.0,Q2,L87H,GBP(millions),Primary income,Balances,"Transactions with non-EU countries 4,5,6"
369,-5339.0,K02000001,2016.0,Q3,L87H,GBP(millions),Primary income,Balances,"Transactions with non-EU countries 4,5,6"
370,-6860.0,K02000001,2016.0,Q4,L87H,GBP(millions),Primary income,Balances,"Transactions with non-EU countries 4,5,6"
371,-3854.0,K02000001,2017.0,Q1,L87H,GBP(millions),Primary income,Balances,"Transactions with non-EU countries 4,5,6"
372,-8080.0,K02000001,2017.0,Q2,L87H,GBP(millions),Primary income,Balances,"Transactions with non-EU countries 4,5,6"
373,-6073.0,K02000001,2017.0,Q3,L87H,GBP(millions),Primary income,Balances,"Transactions with non-EU countries 4,5,6"
374,-11179.0,K02000001,2015.0,,L86F,GBP(millions),Secondary income,Balances,"Transactions with non-EU countries 4,5,6"
375,-12012.0,K02000001,2016.0,,L86F,GBP(millions),Secondary income,Balances,"Transactions with non-EU countries 4,5,6"
376,-2555.0,K02000001,2015.0,Q3,L86F,GBP(millions),Secondary income,Balances,"Transactions with non-EU countries 4,5,6"
377,-3448.0,K02000001,2015.0,Q4,L86F,GBP(millions),Secondary income,Balances,"Transactions with non-EU countries 4,5,6"
378,-2687.0,K02000001,2016.0,Q1,L86F,GBP(millions),Secondary income,Balances,"Transactions with non-EU countries 4,5,6"
379,-3014.0,K02000001,2016.0,Q2,L86F,GBP(millions),Secondary income,Balances,"Transactions with non-EU countries 4,5,6"
380,-2795.0,K02000001,2016.0,Q3,L86F,GBP(millions),Secondary income,Balances,"Transactions with non-EU countries 4,5,6"
381,-3516.0,K02000001,2016.0,Q4,L86F,GBP(millions),Secondary income,Balances,"Transactions with non-EU countries 4,5,6"
382,-2742.0,K02000001,2017.0,Q1,L86F,GBP(millions),Secondary income,Balances,"Transactions with non-EU countries 4,5,6"
383,-2921.0,K02000001,2017.0,Q2,L86F,GBP(millions),Secondary income,Balances,"Transactions with non-EU countries 4,5,6"
384,-2603.0,K02000001,2017.0,Q3,L86F,GBP(millions),Secondary income,Balances,"Transactions with non-EU countries 4,5,6"
385,4180.0,K02000001,2015.0,,L87I,GBP(millions),Total,Balances,"Transactions with non-EU countries 4,5,6"
386,795.0,K02000001,2016.0,,L87I,GBP(millions),Total,Balances,"Transactions with non-EU countries 4,5,6"
387,2919.0,K02000001,2015.0,Q3,L87I,GBP(millions),Total,Balances,"Transactions with non-EU countries 4,5,6"
388,-4274.0,K02000001,2015.0,Q4,L87I,GBP(millions),Total,Balances,"Transactions with non-EU countries 4,5,6"
389,164.0,K02000001,2016.0,Q1,L87I,GBP(millions),Total,Balances,"Transactions with non-EU countries 4,5,6"
390,1640.0,K02000001,2016.0,Q2,L87I,GBP(millions),Total,Balances,"Transactions with non-EU countries 4,5,6"
391,-4428.0,K02000001,2016.0,Q3,L87I,GBP(millions),Total,Balances,"Transactions with non-EU countries 4,5,6"
392,3419.0,K02000001,2016.0,Q4,L87I,GBP(millions),Total,Balances,"Transactions with non-EU countries 4,5,6"
393,4579.0,K02000001,2017.0,Q1,L87I,GBP(millions),Total,Balances,"Transactions with non-EU countries 4,5,6"
394,-95.0,K02000001,2017.0,Q2,L87I,GBP(millions),Total,Balances,"Transactions with non-EU countries 4,5,6"
395,2415.0,K02000001,2017.0,Q3,L87I,GBP(millions),Total,Balances,"Transactions with non-EU countries 4,5,6"

In [29]:
new_table['TIME'] = new_table['Year'].map(lambda cell:cell.replace('.0', ''))
new_table

,OBS,GEOG,Year,Quarter,Code,Currency,Services,Type of Transactions,Transactions Region,TIME
0,138865.0,K02000001,2015.0,,L87S,GBP(millions),Exports of goods,Credits,"Transactions with the European Union 1,2,3,4",2015
1,145471.0,K02000001,2016.0,,L87S,GBP(millions),Exports of goods,Credits,"Transactions with the European Union 1,2,3,4",2016
2,34844.0,K02000001,2015.0,Q3,L87S,GBP(millions),Exports of goods,Credits,"Transactions with the European Union 1,2,3,4",2015
3,34035.0,K02000001,2015.0,Q4,L87S,GBP(millions),Exports of goods,Credits,"Transactions with the European Union 1,2,3,4",2015
4,33205.0,K02000001,2016.0,Q1,L87S,GBP(millions),Exports of goods,Credits,"Transactions with the European Union 1,2,3,4",2016
5,35731.0,K02000001,2016.0,Q2,L87S,GBP(millions),Exports of goods,Credits,"Transactions with the European Union 1,2,3,4",2016
6,37400.0,K02000001,2016.0,Q3,L87S,GBP(millions),Exports of goods,Credits,"Transactions with the European Union 1,2,3,4",2016
7,39135.0,K02000001,2016.0,Q4,L87S,GBP(millions),Exports of goods,Credits,"Transactions with the European Union 1,2,3,4",2016
8,40114.0,K02000001,2017.0,Q1,L87S,GBP(millions),Exports of goods,Credits,"Transactions with the European Union 1,2,3,4",2017
9,41518.0,K02000001,2017.0,Q2,L87S,GBP(millions),Exports of goods,Credits,"Transactions with the European Union 1,2,3,4",2017
10,43231.0,K02000001,2017.0,Q3,L87S,GBP(millions),Exports of goods,Credits,"Transactions with the European Union 1,2,3,4",2017
11,90486.0,K02000001,2015.0,,L854,GBP(millions),Exports of services,Credits,"Transactions with the European Union 1,2,3,4",2015
12,95274.0,K02000001,2016.0,,L854,GBP(millions),Exports of services,Credits,"Transactions with the European Union 1,2,3,4",2016
13,22759.0,K02000001,2015.0,Q3,L854,GBP(millions),Exports of services,Credits,"Transactions with the European Union 1,2,3,4",2015
14,22300.0,K02000001,2015.0,Q4,L854,GBP(millions),Exports of services,Credits,"Transactions with the European Union 1,2,3,4",2015
15,22793.0,K02000001,2016.0,Q1,L854,GBP(millions),Exports of services,Credits,"Transactions with the European Union 1,2,3,4",2016
16,22918.0,K02000001,2016.0,Q2,L854,GBP(millions),Exports of services,Credits,"Transactions with the European Union 1,2,3,4",2016
17,24033.0,K02000001,2016.0,Q3,L854,GBP(millions),Exports of services,Credits,"Transactions with the European Union 1,2,3,4",2016
18,25530.0,K02000001,2016.0,Q4,L854,GBP(millions),Exports of services,Credits,"Transactions with the European Union 1,2,3,4",2016
19,25943.0,K02000001,2017.0,Q1,L854,GBP(millions),Exports of services,Credits,"Transactions with the European Union 1,2,3,4",2017
20,26951.0,K02000001,2017.0,Q2,L854,GBP(millions),Exports of services,Credits,"Transactions with the European Union 1,2,3,4",2017
21,27108.0,K02000001,2017.0,Q3,L854,GBP(millions),Exports of services,Credits,"Transactions with the European Union 1,2,3,4",2017
22,229351.0,K02000001,2015.0,,L84Y,GBP(millions),Total exports of goods and services,Credits,"Transactions with the European Union 1,2,3,4",2015
23,240745.0,K02000001,2016.0,,L84Y,GBP(millions),Total exports of goods and services,Credits,"Transactions with the European Union 1,2,3,4",2016
24,57603.0,K02000001,2015.0,Q3,L84Y,GBP(millions),Total exports of goods and services,Credits,"Transactions with the European Union 1,2,3,4",2015
25,56335.0,K02000001,2015.0,Q4,L84Y,GBP(millions),Total exports of goods and services,Credits,"Transactions with the European Union 1,2,3,4",2015
26,55998.0,K02000001,2016.0,Q1,L84Y,GBP(millions),Total exports of goods and services,Credits,"Transactions with the European Union 1,2,3,4",2016
27,58649.0,K02000001,2016.0,Q2,L84Y,GBP(millions),Total exports of goods and services,Credits,"Transactions with the European Union 1,2,3,4",2016
28,61433.0,K02000001,2016.0,Q3,L84Y,GBP(millions),Total exports of goods and services,Credits,"Transactions with the European Union 1,2,3,4",2016
29,64665.0,K02000001,2016.0,Q4,L84Y,GBP(millions),Total exports of goods and services,Credits,"Transactions with the European Union 1,2,3,4",2016
...,...,...,...,...,...,...,...,...,...,...
366,-11112.0,K02000001,2015.0,Q4,L87H,GBP(millions),Primary income,Balances,"Transactions with non-EU countries 4,5,6",2015
367,-6822.0,K02000001,2016.0,Q1,L87H,GBP(millions),Primary income,Balances,"Transactions with non-EU countries 4,5,6",2016
368,-7158.0,K02000001,2016.0,Q2,L87H,GBP(millions),Primary income,Balances,"Transactions with non-EU countries 4,5,6",2016
369,-5339.0,K02000001,2016.0,Q3,L87H,GBP(millions),Primary income,Balances,"Transactions with non-EU countries 4,5,6",2016
370,-6860.0,K02000001,2016.0,Q4,L87H,GBP(millions),Primary income,Balances,"Transactions with non-EU countries 4,5,6",2016
371,-3854.0,K02000001,2017.0,Q1,L87H,GBP(millions),Primary income,Balances,"Transactions with non-EU countries 4,5,6",2017
372,-8080.0,K02000001,2017.0,Q2,L87H,GBP(millions),Primary income,Balances,"Transactions with non-EU countries 4,5,6",2017
373,-6073.0,K02000001,2017.0,Q3,L87H,GBP(millions),Primary income,Balances,"Transactions with non-EU countries 4,5,6",2017
374,-11179.0,K02000001,2015.0,,L86F,GBP(millions),Secondary income,Balances,"Transactions with non-EU countries 4,5,6",2015
375,-12012.0,K02000001,2016.0,,L86F,GBP(millions),Secondary income,Balances,"Transactions with non-EU countries 4,5,6",2016
376,-2555.0,K02000001,2015.0,Q3,L86F,GBP(millions),Secondary income,Balances,"Transactions with non-EU countries 4,5,6",2015
377,-3448.0,K02000001,2015.0,Q4,L86F,GBP(millions),Secondary income,Balances,"Transactions with non-EU countries 4,5,6",2015
378,-2687.0,K02000001,2016.0,Q1,L86F,GBP(millions),Secondary income,Balances,"Transactions with non-EU countries 4,5,6",2016
379,-3014.0,K02000001,2016.0,Q2,L86F,GBP(millions),Secondary income,Balances,"Transactions with non-EU countries 4,5,6",2016
380,-2795.0,K02000001,2016.0,Q3,L86F,GBP(millions),Secondary income,Balances,"Transactions with non-EU countries 4,5,6",2016
381,-3516.0,K02000001,2016.0,Q4,L86F,GBP(millions),Secondary income,Balances,"Transactions with non-EU countries 4,5,6",2016
382,-2742.0,K02000001,2017.0,Q1,L86F,GBP(millions),Secondary income,Balances,"Transactions with non-EU countries 4,5,6",2017
383,-2921.0,K02000001,2017.0,Q2,L86F,GBP(millions),Secondary income,Balances,"Transactions with non-EU countries 4,5,6",2017
384,-2603.0,K02000001,2017.0,Q3,L86F,GBP(millions),Secondary income,Balances,"Transactions with non-EU countries 4,5,6",2017
385,4180.0,K02000001,2015.0,,L87I,GBP(millions),Total,Balances,"Transactions with non-EU countries 4,5,6",2015
386,795.0,K02000001,2016.0,,L87I,GBP(millions),Total,Balances,"Transactions with non-EU countries 4,5,6",2016
387,2919.0,K02000001,2015.0,Q3,L87I,GBP(millions),Total,Balances,"Transactions with non-EU countries 4,5,6",2015
388,-4274.0,K02000001,2015.0,Q4,L87I,GBP(millions),Total,Balances,"Transactions with non-EU countries 4,5,6",2015
389,164.0,K02000001,2016.0,Q1,L87I,GBP(millions),Total,Balances,"Transactions with non-EU countries 4,5,6",2016
390,1640.0,K02000001,2016.0,Q2,L87I,GBP(millions),Total,Balances,"Transactions with non-EU countries 4,5,6",2016
391,-4428.0,K02000001,2016.0,Q3,L87I,GBP(millions),Total,Balances,"Transactions with non-EU countries 4,5,6",2016
392,3419.0,K02000001,2016.0,Q4,L87I,GBP(millions),Total,Balances,"Transactions with non-EU countries 4,5,6",2016
393,4579.0,K02000001,2017.0,Q1,L87I,GBP(millions),Total,Balances,"Transactions with non-EU countries 4,5,6",2017
394,-95.0,K02000001,2017.0,Q2,L87I,GBP(millions),Total,Balances,"Transactions with non-EU countries 4,5,6",2017
395,2415.0,K02000001,2017.0,Q3,L87I,GBP(millions),Total,Balances,"Transactions with non-EU countries 4,5,6",2017

In [30]:
print(len(new_table))
new_table['TIME'] = new_table['TIME'].map(str) + new_table['Quarter']

396

In [31]:
print(len(new_table))
new_table

396

,OBS,GEOG,Year,Quarter,Code,Currency,Services,Type of Transactions,Transactions Region,TIME
0,138865.0,K02000001,2015.0,,L87S,GBP(millions),Exports of goods,Credits,"Transactions with the European Union 1,2,3,4",2015
1,145471.0,K02000001,2016.0,,L87S,GBP(millions),Exports of goods,Credits,"Transactions with the European Union 1,2,3,4",2016
2,34844.0,K02000001,2015.0,Q3,L87S,GBP(millions),Exports of goods,Credits,"Transactions with the European Union 1,2,3,4",2015 Q3
3,34035.0,K02000001,2015.0,Q4,L87S,GBP(millions),Exports of goods,Credits,"Transactions with the European Union 1,2,3,4",2015 Q4
4,33205.0,K02000001,2016.0,Q1,L87S,GBP(millions),Exports of goods,Credits,"Transactions with the European Union 1,2,3,4",2016 Q1
5,35731.0,K02000001,2016.0,Q2,L87S,GBP(millions),Exports of goods,Credits,"Transactions with the European Union 1,2,3,4",2016 Q2
6,37400.0,K02000001,2016.0,Q3,L87S,GBP(millions),Exports of goods,Credits,"Transactions with the European Union 1,2,3,4",2016 Q3
7,39135.0,K02000001,2016.0,Q4,L87S,GBP(millions),Exports of goods,Credits,"Transactions with the European Union 1,2,3,4",2016 Q4
8,40114.0,K02000001,2017.0,Q1,L87S,GBP(millions),Exports of goods,Credits,"Transactions with the European Union 1,2,3,4",2017 Q1
9,41518.0,K02000001,2017.0,Q2,L87S,GBP(millions),Exports of goods,Credits,"Transactions with the European Union 1,2,3,4",2017 Q2
10,43231.0,K02000001,2017.0,Q3,L87S,GBP(millions),Exports of goods,Credits,"Transactions with the European Union 1,2,3,4",2017 Q3
11,90486.0,K02000001,2015.0,,L854,GBP(millions),Exports of services,Credits,"Transactions with the European Union 1,2,3,4",2015
12,95274.0,K02000001,2016.0,,L854,GBP(millions),Exports of services,Credits,"Transactions with the European Union 1,2,3,4",2016
13,22759.0,K02000001,2015.0,Q3,L854,GBP(millions),Exports of services,Credits,"Transactions with the European Union 1,2,3,4",2015 Q3
14,22300.0,K02000001,2015.0,Q4,L854,GBP(millions),Exports of services,Credits,"Transactions with the European Union 1,2,3,4",2015 Q4
15,22793.0,K02000001,2016.0,Q1,L854,GBP(millions),Exports of services,Credits,"Transactions with the European Union 1,2,3,4",2016 Q1
16,22918.0,K02000001,2016.0,Q2,L854,GBP(millions),Exports of services,Credits,"Transactions with the European Union 1,2,3,4",2016 Q2
17,24033.0,K02000001,2016.0,Q3,L854,GBP(millions),Exports of services,Credits,"Transactions with the European Union 1,2,3,4",2016 Q3
18,25530.0,K02000001,2016.0,Q4,L854,GBP(millions),Exports of services,Credits,"Transactions with the European Union 1,2,3,4",2016 Q4
19,25943.0,K02000001,2017.0,Q1,L854,GBP(millions),Exports of services,Credits,"Transactions with the European Union 1,2,3,4",2017 Q1
20,26951.0,K02000001,2017.0,Q2,L854,GBP(millions),Exports of services,Credits,"Transactions with the European Union 1,2,3,4",2017 Q2
21,27108.0,K02000001,2017.0,Q3,L854,GBP(millions),Exports of services,Credits,"Transactions with the European Union 1,2,3,4",2017 Q3
22,229351.0,K02000001,2015.0,,L84Y,GBP(millions),Total exports of goods and services,Credits,"Transactions with the European Union 1,2,3,4",2015
23,240745.0,K02000001,2016.0,,L84Y,GBP(millions),Total exports of goods and services,Credits,"Transactions with the European Union 1,2,3,4",2016
24,57603.0,K02000001,2015.0,Q3,L84Y,GBP(millions),Total exports of goods and services,Credits,"Transactions with the European Union 1,2,3,4",2015 Q3
25,56335.0,K02000001,2015.0,Q4,L84Y,GBP(millions),Total exports of goods and services,Credits,"Transactions with the European Union 1,2,3,4",2015 Q4
26,55998.0,K02000001,2016.0,Q1,L84Y,GBP(millions),Total exports of goods and services,Credits,"Transactions with the European Union 1,2,3,4",2016 Q1
27,58649.0,K02000001,2016.0,Q2,L84Y,GBP(millions),Total exports of goods and services,Credits,"Transactions with the European Union 1,2,3,4",2016 Q2
28,61433.0,K02000001,2016.0,Q3,L84Y,GBP(millions),Total exports of goods and services,Credits,"Transactions with the European Union 1,2,3,4",2016 Q3
29,64665.0,K02000001,2016.0,Q4,L84Y,GBP(millions),Total exports of goods and services,Credits,"Transactions with the European Union 1,2,3,4",2016 Q4
...,...,...,...,...,...,...,...,...,...,...
366,-11112.0,K02000001,2015.0,Q4,L87H,GBP(millions),Primary income,Balances,"Transactions with non-EU countries 4,5,6",2015 Q4
367,-6822.0,K02000001,2016.0,Q1,L87H,GBP(millions),Primary income,Balances,"Transactions with non-EU countries 4,5,6",2016 Q1
368,-7158.0,K02000001,2016.0,Q2,L87H,GBP(millions),Primary income,Balances,"Transactions with non-EU countries 4,5,6",2016 Q2
369,-5339.0,K02000001,2016.0,Q3,L87H,GBP(millions),Primary income,Balances,"Transactions with non-EU countries 4,5,6",2016 Q3
370,-6860.0,K02000001,2016.0,Q4,L87H,GBP(millions),Primary income,Balances,"Transactions with non-EU countries 4,5,6",2016 Q4
371,-3854.0,K02000001,2017.0,Q1,L87H,GBP(millions),Primary income,Balances,"Transactions with non-EU countries 4,5,6",2017 Q1
372,-8080.0,K02000001,2017.0,Q2,L87H,GBP(millions),Primary income,Balances,"Transactions with non-EU countries 4,5,6",2017 Q2
373,-6073.0,K02000001,2017.0,Q3,L87H,GBP(millions),Primary income,Balances,"Transactions with non-EU countries 4,5,6",2017 Q3
374,-11179.0,K02000001,2015.0,,L86F,GBP(millions),Secondary income,Balances,"Transactions with non-EU countries 4,5,6",2015
375,-12012.0,K02000001,2016.0,,L86F,GBP(millions),Secondary income,Balances,"Transactions with non-EU countries 4,5,6",2016
376,-2555.0,K02000001,2015.0,Q3,L86F,GBP(millions),Secondary income,Balances,"Transactions with non-EU countries 4,5,6",2015 Q3
377,-3448.0,K02000001,2015.0,Q4,L86F,GBP(millions),Secondary income,Balances,"Transactions with non-EU countries 4,5,6",2015 Q4
378,-2687.0,K02000001,2016.0,Q1,L86F,GBP(millions),Secondary income,Balances,"Transactions with non-EU countries 4,5,6",2016 Q1
379,-3014.0,K02000001,2016.0,Q2,L86F,GBP(millions),Secondary income,Balances,"Transactions with non-EU countries 4,5,6",2016 Q2
380,-2795.0,K02000001,2016.0,Q3,L86F,GBP(millions),Secondary income,Balances,"Transactions with non-EU countries 4,5,6",2016 Q3
381,-3516.0,K02000001,2016.0,Q4,L86F,GBP(millions),Secondary income,Balances,"Transactions with non-EU countries 4,5,6",2016 Q4
382,-2742.0,K02000001,2017.0,Q1,L86F,GBP(millions),Secondary income,Balances,"Transactions with non-EU countries 4,5,6",2017 Q1
383,-2921.0,K02000001,2017.0,Q2,L86F,GBP(millions),Secondary income,Balances,"Transactions with non-EU countries 4,5,6",2017 Q2
384,-2603.0,K02000001,2017.0,Q3,L86F,GBP(millions),Secondary income,Balances,"Transactions with non-EU countries 4,5,6",2017 Q3
385,4180.0,K02000001,2015.0,,L87I,GBP(millions),Total,Balances,"Transactions with non-EU countries 4,5,6",2015
386,795.0,K02000001,2016.0,,L87I,GBP(millions),Total,Balances,"Transactions with non-EU countries 4,5,6",2016
387,2919.0,K02000001,2015.0,Q3,L87I,GBP(millions),Total,Balances,"Transactions with non-EU countries 4,5,6",2015 Q3
388,-4274.0,K02000001,2015.0,Q4,L87I,GBP(millions),Total,Balances,"Transactions with non-EU countries 4,5,6",2015 Q4
389,164.0,K02000001,2016.0,Q1,L87I,GBP(millions),Total,Balances,"Transactions with non-EU countries 4,5,6",2016 Q1
390,1640.0,K02000001,2016.0,Q2,L87I,GBP(millions),Total,Balances,"Transactions with non-EU countries 4,5,6",2016 Q2
391,-4428.0,K02000001,2016.0,Q3,L87I,GBP(millions),Total,Balances,"Transactions with non-EU countries 4,5,6",2016 Q3
392,3419.0,K02000001,2016.0,Q4,L87I,GBP(millions),Total,Balances,"Transactions with non-EU countries 4,5,6",2016 Q4
393,4579.0,K02000001,2017.0,Q1,L87I,GBP(millions),Total,Balances,"Transactions with non-EU countries 4,5,6",2017 Q1
394,-95.0,K02000001,2017.0,Q2,L87I,GBP(millions),Total,Balances,"Transactions with non-EU countries 4,5,6",2017 Q2
395,2415.0,K02000001,2017.0,Q3,L87I,GBP(millions),Total,Balances,"Transactions with non-EU countries 4,5,6",2017 Q3

In [32]:
new_table = new_table.drop('Year', axis=1)
new_table = new_table.drop('Quarter', axis=1)

In [33]:
print(len(new_table))
new_table

396

,OBS,GEOG,Code,Currency,Services,Type of Transactions,Transactions Region,TIME
0,138865.0,K02000001,L87S,GBP(millions),Exports of goods,Credits,"Transactions with the European Union 1,2,3,4",2015
1,145471.0,K02000001,L87S,GBP(millions),Exports of goods,Credits,"Transactions with the European Union 1,2,3,4",2016
2,34844.0,K02000001,L87S,GBP(millions),Exports of goods,Credits,"Transactions with the European Union 1,2,3,4",2015 Q3
3,34035.0,K02000001,L87S,GBP(millions),Exports of goods,Credits,"Transactions with the European Union 1,2,3,4",2015 Q4
4,33205.0,K02000001,L87S,GBP(millions),Exports of goods,Credits,"Transactions with the European Union 1,2,3,4",2016 Q1
5,35731.0,K02000001,L87S,GBP(millions),Exports of goods,Credits,"Transactions with the European Union 1,2,3,4",2016 Q2
6,37400.0,K02000001,L87S,GBP(millions),Exports of goods,Credits,"Transactions with the European Union 1,2,3,4",2016 Q3
7,39135.0,K02000001,L87S,GBP(millions),Exports of goods,Credits,"Transactions with the European Union 1,2,3,4",2016 Q4
8,40114.0,K02000001,L87S,GBP(millions),Exports of goods,Credits,"Transactions with the European Union 1,2,3,4",2017 Q1
9,41518.0,K02000001,L87S,GBP(millions),Exports of goods,Credits,"Transactions with the European Union 1,2,3,4",2017 Q2
10,43231.0,K02000001,L87S,GBP(millions),Exports of goods,Credits,"Transactions with the European Union 1,2,3,4",2017 Q3
11,90486.0,K02000001,L854,GBP(millions),Exports of services,Credits,"Transactions with the European Union 1,2,3,4",2015
12,95274.0,K02000001,L854,GBP(millions),Exports of services,Credits,"Transactions with the European Union 1,2,3,4",2016
13,22759.0,K02000001,L854,GBP(millions),Exports of services,Credits,"Transactions with the European Union 1,2,3,4",2015 Q3
14,22300.0,K02000001,L854,GBP(millions),Exports of services,Credits,"Transactions with the European Union 1,2,3,4",2015 Q4
15,22793.0,K02000001,L854,GBP(millions),Exports of services,Credits,"Transactions with the European Union 1,2,3,4",2016 Q1
16,22918.0,K02000001,L854,GBP(millions),Exports of services,Credits,"Transactions with the European Union 1,2,3,4",2016 Q2
17,24033.0,K02000001,L854,GBP(millions),Exports of services,Credits,"Transactions with the European Union 1,2,3,4",2016 Q3
18,25530.0,K02000001,L854,GBP(millions),Exports of services,Credits,"Transactions with the European Union 1,2,3,4",2016 Q4
19,25943.0,K02000001,L854,GBP(millions),Exports of services,Credits,"Transactions with the European Union 1,2,3,4",2017 Q1
20,26951.0,K02000001,L854,GBP(millions),Exports of services,Credits,"Transactions with the European Union 1,2,3,4",2017 Q2
21,27108.0,K02000001,L854,GBP(millions),Exports of services,Credits,"Transactions with the European Union 1,2,3,4",2017 Q3
22,229351.0,K02000001,L84Y,GBP(millions),Total exports of goods and services,Credits,"Transactions with the European Union 1,2,3,4",2015
23,240745.0,K02000001,L84Y,GBP(millions),Total exports of goods and services,Credits,"Transactions with the European Union 1,2,3,4",2016
24,57603.0,K02000001,L84Y,GBP(millions),Total exports of goods and services,Credits,"Transactions with the European Union 1,2,3,4",2015 Q3
25,56335.0,K02000001,L84Y,GBP(millions),Total exports of goods and services,Credits,"Transactions with the European Union 1,2,3,4",2015 Q4
26,55998.0,K02000001,L84Y,GBP(millions),Total exports of goods and services,Credits,"Transactions with the European Union 1,2,3,4",2016 Q1
27,58649.0,K02000001,L84Y,GBP(millions),Total exports of goods and services,Credits,"Transactions with the European Union 1,2,3,4",2016 Q2
28,61433.0,K02000001,L84Y,GBP(millions),Total exports of goods and services,Credits,"Transactions with the European Union 1,2,3,4",2016 Q3
29,64665.0,K02000001,L84Y,GBP(millions),Total exports of goods and services,Credits,"Transactions with the European Union 1,2,3,4",2016 Q4
...,...,...,...,...,...,...,...,...
366,-11112.0,K02000001,L87H,GBP(millions),Primary income,Balances,"Transactions with non-EU countries 4,5,6",2015 Q4
367,-6822.0,K02000001,L87H,GBP(millions),Primary income,Balances,"Transactions with non-EU countries 4,5,6",2016 Q1
368,-7158.0,K02000001,L87H,GBP(millions),Primary income,Balances,"Transactions with non-EU countries 4,5,6",2016 Q2
369,-5339.0,K02000001,L87H,GBP(millions),Primary income,Balances,"Transactions with non-EU countries 4,5,6",2016 Q3
370,-6860.0,K02000001,L87H,GBP(millions),Primary income,Balances,"Transactions with non-EU countries 4,5,6",2016 Q4
371,-3854.0,K02000001,L87H,GBP(millions),Primary income,Balances,"Transactions with non-EU countries 4,5,6",2017 Q1
372,-8080.0,K02000001,L87H,GBP(millions),Primary income,Balances,"Transactions with non-EU countries 4,5,6",2017 Q2
373,-6073.0,K02000001,L87H,GBP(millions),Primary income,Balances,"Transactions with non-EU countries 4,5,6",2017 Q3
374,-11179.0,K02000001,L86F,GBP(millions),Secondary income,Balances,"Transactions with non-EU countries 4,5,6",2015
375,-12012.0,K02000001,L86F,GBP(millions),Secondary income,Balances,"Transactions with non-EU countries 4,5,6",2016
376,-2555.0,K02000001,L86F,GBP(millions),Secondary income,Balances,"Transactions with non-EU countries 4,5,6",2015 Q3
377,-3448.0,K02000001,L86F,GBP(millions),Secondary income,Balances,"Transactions with non-EU countries 4,5,6",2015 Q4
378,-2687.0,K02000001,L86F,GBP(millions),Secondary income,Balances,"Transactions with non-EU countries 4,5,6",2016 Q1
379,-3014.0,K02000001,L86F,GBP(millions),Secondary income,Balances,"Transactions with non-EU countries 4,5,6",2016 Q2
380,-2795.0,K02000001,L86F,GBP(millions),Secondary income,Balances,"Transactions with non-EU countries 4,5,6",2016 Q3
381,-3516.0,K02000001,L86F,GBP(millions),Secondary income,Balances,"Transactions with non-EU countries 4,5,6",2016 Q4
382,-2742.0,K02000001,L86F,GBP(millions),Secondary income,Balances,"Transactions with non-EU countries 4,5,6",2017 Q1
383,-2921.0,K02000001,L86F,GBP(millions),Secondary income,Balances,"Transactions with non-EU countries 4,5,6",2017 Q2
384,-2603.0,K02000001,L86F,GBP(millions),Secondary income,Balances,"Transactions with non-EU countries 4,5,6",2017 Q3
385,4180.0,K02000001,L87I,GBP(millions),Total,Balances,"Transactions with non-EU countries 4,5,6",2015
386,795.0,K02000001,L87I,GBP(millions),Total,Balances,"Transactions with non-EU countries 4,5,6",2016
387,2919.0,K02000001,L87I,GBP(millions),Total,Balances,"Transactions with non-EU countries 4,5,6",2015 Q3
388,-4274.0,K02000001,L87I,GBP(millions),Total,Balances,"Transactions with non-EU countries 4,5,6",2015 Q4
389,164.0,K02000001,L87I,GBP(millions),Total,Balances,"Transactions with non-EU countries 4,5,6",2016 Q1
390,1640.0,K02000001,L87I,GBP(millions),Total,Balances,"Transactions with non-EU countries 4,5,6",2016 Q2
391,-4428.0,K02000001,L87I,GBP(millions),Total,Balances,"Transactions with non-EU countries 4,5,6",2016 Q3
392,3419.0,K02000001,L87I,GBP(millions),Total,Balances,"Transactions with non-EU countries 4,5,6",2016 Q4
393,4579.0,K02000001,L87I,GBP(millions),Total,Balances,"Transactions with non-EU countries 4,5,6",2017 Q1
394,-95.0,K02000001,L87I,GBP(millions),Total,Balances,"Transactions with non-EU countries 4,5,6",2017 Q2
395,2415.0,K02000001,L87I,GBP(millions),Total,Balances,"Transactions with non-EU countries 4,5,6",2017 Q3

In [43]:
new_table['Transactions Region'] = new_table['Transactions Region'].map(lambda x: x.rstrip('123456,'))

In [45]:
new_table.tail(5)

,OBS,GEOG,Code,Currency,Services,Type of Transactions,Transactions Region,TIME
391,-4428.0,K02000001,L87I,GBP(millions),Total,Balances,Transactions with non-EU countries,2016 Q3
392,3419.0,K02000001,L87I,GBP(millions),Total,Balances,Transactions with non-EU countries,2016 Q4
393,4579.0,K02000001,L87I,GBP(millions),Total,Balances,Transactions with non-EU countries,2017 Q1
394,-95.0,K02000001,L87I,GBP(millions),Total,Balances,Transactions with non-EU countries,2017 Q2
395,2415.0,K02000001,L87I,GBP(millions),Total,Balances,Transactions with non-EU countries,2017 Q3

In [46]:

new_table.fillna('', inplace=True)

writetechnicalCSV('balanceofpayments2017q3tabc.csv', new_table)

writing 1 conversion segments into C:\Users\vamsi\balanceofpayments2017q3tabc.csv
pdconversionwrite segment size 396