###  Balanceofpayments2017q3, Tab B

In [1]:
from databaker.framework import *

In [2]:
import pandas as pd

In [3]:
inputFile = 'balanceofpayments2017q3.xls'

In [4]:
tab = loadxlstabs(inputFile)

Loading balanceofpayments2017q3.xls which has size 309248 bytes
Table names: ['Index', 'Records', 'Table A', 'Table B', 'Table C', 'Table D', 'Table E', 'Table F', 'Table G', 'Table H', 'Table I', 'Table J', 'Table K', 'Table R1', 'Table R2', 'Table R3']

In [5]:
tab = tab[3]

In [6]:
savepreviewhtml(tab)

In [7]:
observations = tab.excel_ref('D9').expand(DOWN).expand(RIGHT).is_not_blank()

In [8]:
savepreviewhtml(observations)

In [9]:
Code = tab.excel_ref('C9').expand(DOWN).is_not_blank()

In [10]:
savepreviewhtml(Code)

In [11]:
Year = tab.excel_ref('D4').expand(RIGHT).is_not_blank()
Quarter = tab.excel_ref('D5').expand(RIGHT)

In [12]:
savepreviewhtml(Year)

In [13]:
savepreviewhtml(Quarter)

In [14]:
Account = tab.excel_ref('B').expand(DOWN).by_index([7,27,47,67]) - tab.excel_ref('B78').expand(DOWN)

In [15]:
savepreviewhtml(Account)

In [16]:
Services = tab.excel_ref('B').expand(DOWN).by_index([8,13,19,28,33,39,48,53,59,68,25,45,65,76])

In [17]:
savepreviewhtml(Services)

In [18]:
Nettransactions = tab.excel_ref('B').is_not_blank().is_not_whitespace() - Account - Services

In [19]:
Nettransactions = Nettransactions - tab.excel_ref('B78').expand(DOWN) -tab.excel_ref('B2').expand(UP)

In [20]:
savepreviewhtml(Nettransactions)

In [21]:
Currency = tab.excel_ref('N3')

In [22]:
savepreviewhtml(Currency)

In [23]:
Dimensions = [
            HDimConst('GEOG', 'K02000001'),
            HDim(Year,'Year',DIRECTLY,ABOVE),
            HDim(Quarter,'Quarter',DIRECTLY,ABOVE),
            HDim(Code,'Code Identifier',DIRECTLY,LEFT),
            HDimConst('Currency', 'GBP(millions)'),            
            HDim(Nettransactions,'Type of Services',DIRECTLY,LEFT),
            HDim(Services,'Services',CLOSEST, ABOVE),
            HDim(Account,'Account Transactions',CLOSEST,ABOVE)
            
    
]

In [24]:
c1 = ConversionSegment(observations, Dimensions, processTIMEUNIT=True)
savepreviewhtml(c1)

In [25]:
new_table = c1.topandas()
new_table

,OBS,GEOG,Year,Quarter,Code,Currency,Type of Services,Services,Account Transactions
0,288770.0,K02000001,2015.0,,BOKG,GBP(millions),Exports of goods,Exports of goods and services,Credits
1,302067.0,K02000001,2016.0,,BOKG,GBP(millions),Exports of goods,Exports of goods and services,Credits
2,71012.0,K02000001,2015.0,Q3,BOKG,GBP(millions),Exports of goods,Exports of goods and services,Credits
3,71109.0,K02000001,2015.0,Q4,BOKG,GBP(millions),Exports of goods,Exports of goods and services,Credits
4,69916.0,K02000001,2016.0,Q1,BOKG,GBP(millions),Exports of goods,Exports of goods and services,Credits
5,74991.0,K02000001,2016.0,Q2,BOKG,GBP(millions),Exports of goods,Exports of goods and services,Credits
6,74951.0,K02000001,2016.0,Q3,BOKG,GBP(millions),Exports of goods,Exports of goods and services,Credits
7,82209.0,K02000001,2016.0,Q4,BOKG,GBP(millions),Exports of goods,Exports of goods and services,Credits
8,83512.0,K02000001,2017.0,Q1,BOKG,GBP(millions),Exports of goods,Exports of goods and services,Credits
9,86114.0,K02000001,2017.0,Q2,BOKG,GBP(millions),Exports of goods,Exports of goods and services,Credits
10,86841.0,K02000001,2017.0,Q3,BOKG,GBP(millions),Exports of goods,Exports of goods and services,Credits
11,228391.0,K02000001,2015.0,,IKBB,GBP(millions),Exports of services,Exports of goods and services,Credits
12,252671.0,K02000001,2016.0,,IKBB,GBP(millions),Exports of services,Exports of goods and services,Credits
13,56255.0,K02000001,2015.0,Q3,IKBB,GBP(millions),Exports of services,Exports of goods and services,Credits
14,58442.0,K02000001,2015.0,Q4,IKBB,GBP(millions),Exports of services,Exports of goods and services,Credits
15,60042.0,K02000001,2016.0,Q1,IKBB,GBP(millions),Exports of services,Exports of goods and services,Credits
16,61808.0,K02000001,2016.0,Q2,IKBB,GBP(millions),Exports of services,Exports of goods and services,Credits
17,63653.0,K02000001,2016.0,Q3,IKBB,GBP(millions),Exports of services,Exports of goods and services,Credits
18,67168.0,K02000001,2016.0,Q4,IKBB,GBP(millions),Exports of services,Exports of goods and services,Credits
19,68127.0,K02000001,2017.0,Q1,IKBB,GBP(millions),Exports of services,Exports of goods and services,Credits
20,68769.0,K02000001,2017.0,Q2,IKBB,GBP(millions),Exports of services,Exports of goods and services,Credits
21,69985.0,K02000001,2017.0,Q3,IKBB,GBP(millions),Exports of services,Exports of goods and services,Credits
22,517161.0,K02000001,2015.0,,IKBH,GBP(millions),Total exports of goods and services,Exports of goods and services,Credits
23,554738.0,K02000001,2016.0,,IKBH,GBP(millions),Total exports of goods and services,Exports of goods and services,Credits
24,127267.0,K02000001,2015.0,Q3,IKBH,GBP(millions),Total exports of goods and services,Exports of goods and services,Credits
25,129551.0,K02000001,2015.0,Q4,IKBH,GBP(millions),Total exports of goods and services,Exports of goods and services,Credits
26,129958.0,K02000001,2016.0,Q1,IKBH,GBP(millions),Total exports of goods and services,Exports of goods and services,Credits
27,136799.0,K02000001,2016.0,Q2,IKBH,GBP(millions),Total exports of goods and services,Exports of goods and services,Credits
28,138604.0,K02000001,2016.0,Q3,IKBH,GBP(millions),Total exports of goods and services,Exports of goods and services,Credits
29,149377.0,K02000001,2016.0,Q4,IKBH,GBP(millions),Total exports of goods and services,Exports of goods and services,Credits
...,...,...,...,...,...,...,...,...,...
399,-3.8,K02000001,2015.0,Q4,D28M,GBP(millions),Total primary income,Trade in goods and services,Balances as a percentage of GDP1
400,-3.1,K02000001,2016.0,Q1,D28M,GBP(millions),Total primary income,Trade in goods and services,Balances as a percentage of GDP1
401,-2.9,K02000001,2016.0,Q2,D28M,GBP(millions),Total primary income,Trade in goods and services,Balances as a percentage of GDP1
402,-2.2,K02000001,2016.0,Q3,D28M,GBP(millions),Total primary income,Trade in goods and services,Balances as a percentage of GDP1
403,-2.0,K02000001,2016.0,Q4,D28M,GBP(millions),Total primary income,Trade in goods and services,Balances as a percentage of GDP1
404,-1.7,K02000001,2017.0,Q1,D28M,GBP(millions),Total primary income,Trade in goods and services,Balances as a percentage of GDP1
405,-2.6,K02000001,2017.0,Q2,D28M,GBP(millions),Total primary income,Trade in goods and services,Balances as a percentage of GDP1
406,-2.2,K02000001,2017.0,Q3,D28M,GBP(millions),Total primary income,Trade in goods and services,Balances as a percentage of GDP1
407,-1.2,K02000001,2015.0,,D28N,GBP(millions),Total secondary income,Trade in goods and services,Balances as a percentage of GDP1
408,-1.1,K02000001,2016.0,,D28N,GBP(millions),Total secondary income,Trade in goods and services,Balances as a percentage of GDP1
409,-0.9,K02000001,2015.0,Q3,D28N,GBP(millions),Total secondary income,Trade in goods and services,Balances as a percentage of GDP1
410,-1.6,K02000001,2015.0,Q4,D28N,GBP(millions),Total secondary income,Trade in goods and services,Balances as a percentage of GDP1
411,-1.1,K02000001,2016.0,Q1,D28N,GBP(millions),Total secondary income,Trade in goods and services,Balances as a percentage of GDP1
412,-1.1,K02000001,2016.0,Q2,D28N,GBP(millions),Total secondary income,Trade in goods and services,Balances as a percentage of GDP1
413,-1.2,K02000001,2016.0,Q3,D28N,GBP(millions),Total secondary income,Trade in goods and services,Balances as a percentage of GDP1
414,-1.2,K02000001,2016.0,Q4,D28N,GBP(millions),Total secondary income,Trade in goods and services,Balances as a percentage of GDP1
415,-0.9,K02000001,2017.0,Q1,D28N,GBP(millions),Total secondary income,Trade in goods and services,Balances as a percentage of GDP1
416,-1.3,K02000001,2017.0,Q2,D28N,GBP(millions),Total secondary income,Trade in goods and services,Balances as a percentage of GDP1
417,-1.1,K02000001,2017.0,Q3,D28N,GBP(millions),Total secondary income,Trade in goods and services,Balances as a percentage of GDP1
418,-5.2,K02000001,2015.0,,AA6H,GBP(millions),None,Current balance as percentage of GDP,Balances as a percentage of GDP1
419,-5.8,K02000001,2016.0,,AA6H,GBP(millions),None,Current balance as percentage of GDP,Balances as a percentage of GDP1
420,-4.3,K02000001,2015.0,Q3,AA6H,GBP(millions),None,Current balance as percentage of GDP,Balances as a percentage of GDP1
421,-7.1,K02000001,2015.0,Q4,AA6H,GBP(millions),None,Current balance as percentage of GDP,Balances as a percentage of GDP1
422,-6.2,K02000001,2016.0,Q1,AA6H,GBP(millions),None,Current balance as percentage of GDP,Balances as a percentage of GDP1
423,-5.6,K02000001,2016.0,Q2,AA6H,GBP(millions),None,Current balance as percentage of GDP,Balances as a percentage of GDP1
424,-6.8,K02000001,2016.0,Q3,AA6H,GBP(millions),None,Current balance as percentage of GDP,Balances as a percentage of GDP1
425,-4.6,K02000001,2016.0,Q4,AA6H,GBP(millions),None,Current balance as percentage of GDP,Balances as a percentage of GDP1
426,-4.3,K02000001,2017.0,Q1,AA6H,GBP(millions),None,Current balance as percentage of GDP,Balances as a percentage of GDP1
427,-5.1,K02000001,2017.0,Q2,AA6H,GBP(millions),None,Current balance as percentage of GDP,Balances as a percentage of GDP1
428,-4.5,K02000001,2017.0,Q3,AA6H,GBP(millions),None,Current balance as percentage of GDP,Balances as a percentage of GDP1

In [26]:
new_table['TIME'] = new_table['Year'].map(lambda cell:cell.replace('.0', ''))
new_table

,OBS,GEOG,Year,Quarter,Code,Currency,Type of Services,Services,Account Transactions,TIME
0,288770.0,K02000001,2015.0,,BOKG,GBP(millions),Exports of goods,Exports of goods and services,Credits,2015
1,302067.0,K02000001,2016.0,,BOKG,GBP(millions),Exports of goods,Exports of goods and services,Credits,2016
2,71012.0,K02000001,2015.0,Q3,BOKG,GBP(millions),Exports of goods,Exports of goods and services,Credits,2015
3,71109.0,K02000001,2015.0,Q4,BOKG,GBP(millions),Exports of goods,Exports of goods and services,Credits,2015
4,69916.0,K02000001,2016.0,Q1,BOKG,GBP(millions),Exports of goods,Exports of goods and services,Credits,2016
5,74991.0,K02000001,2016.0,Q2,BOKG,GBP(millions),Exports of goods,Exports of goods and services,Credits,2016
6,74951.0,K02000001,2016.0,Q3,BOKG,GBP(millions),Exports of goods,Exports of goods and services,Credits,2016
7,82209.0,K02000001,2016.0,Q4,BOKG,GBP(millions),Exports of goods,Exports of goods and services,Credits,2016
8,83512.0,K02000001,2017.0,Q1,BOKG,GBP(millions),Exports of goods,Exports of goods and services,Credits,2017
9,86114.0,K02000001,2017.0,Q2,BOKG,GBP(millions),Exports of goods,Exports of goods and services,Credits,2017
10,86841.0,K02000001,2017.0,Q3,BOKG,GBP(millions),Exports of goods,Exports of goods and services,Credits,2017
11,228391.0,K02000001,2015.0,,IKBB,GBP(millions),Exports of services,Exports of goods and services,Credits,2015
12,252671.0,K02000001,2016.0,,IKBB,GBP(millions),Exports of services,Exports of goods and services,Credits,2016
13,56255.0,K02000001,2015.0,Q3,IKBB,GBP(millions),Exports of services,Exports of goods and services,Credits,2015
14,58442.0,K02000001,2015.0,Q4,IKBB,GBP(millions),Exports of services,Exports of goods and services,Credits,2015
15,60042.0,K02000001,2016.0,Q1,IKBB,GBP(millions),Exports of services,Exports of goods and services,Credits,2016
16,61808.0,K02000001,2016.0,Q2,IKBB,GBP(millions),Exports of services,Exports of goods and services,Credits,2016
17,63653.0,K02000001,2016.0,Q3,IKBB,GBP(millions),Exports of services,Exports of goods and services,Credits,2016
18,67168.0,K02000001,2016.0,Q4,IKBB,GBP(millions),Exports of services,Exports of goods and services,Credits,2016
19,68127.0,K02000001,2017.0,Q1,IKBB,GBP(millions),Exports of services,Exports of goods and services,Credits,2017
20,68769.0,K02000001,2017.0,Q2,IKBB,GBP(millions),Exports of services,Exports of goods and services,Credits,2017
21,69985.0,K02000001,2017.0,Q3,IKBB,GBP(millions),Exports of services,Exports of goods and services,Credits,2017
22,517161.0,K02000001,2015.0,,IKBH,GBP(millions),Total exports of goods and services,Exports of goods and services,Credits,2015
23,554738.0,K02000001,2016.0,,IKBH,GBP(millions),Total exports of goods and services,Exports of goods and services,Credits,2016
24,127267.0,K02000001,2015.0,Q3,IKBH,GBP(millions),Total exports of goods and services,Exports of goods and services,Credits,2015
25,129551.0,K02000001,2015.0,Q4,IKBH,GBP(millions),Total exports of goods and services,Exports of goods and services,Credits,2015
26,129958.0,K02000001,2016.0,Q1,IKBH,GBP(millions),Total exports of goods and services,Exports of goods and services,Credits,2016
27,136799.0,K02000001,2016.0,Q2,IKBH,GBP(millions),Total exports of goods and services,Exports of goods and services,Credits,2016
28,138604.0,K02000001,2016.0,Q3,IKBH,GBP(millions),Total exports of goods and services,Exports of goods and services,Credits,2016
29,149377.0,K02000001,2016.0,Q4,IKBH,GBP(millions),Total exports of goods and services,Exports of goods and services,Credits,2016
...,...,...,...,...,...,...,...,...,...,...
399,-3.8,K02000001,2015.0,Q4,D28M,GBP(millions),Total primary income,Trade in goods and services,Balances as a percentage of GDP1,2015
400,-3.1,K02000001,2016.0,Q1,D28M,GBP(millions),Total primary income,Trade in goods and services,Balances as a percentage of GDP1,2016
401,-2.9,K02000001,2016.0,Q2,D28M,GBP(millions),Total primary income,Trade in goods and services,Balances as a percentage of GDP1,2016
402,-2.2,K02000001,2016.0,Q3,D28M,GBP(millions),Total primary income,Trade in goods and services,Balances as a percentage of GDP1,2016
403,-2.0,K02000001,2016.0,Q4,D28M,GBP(millions),Total primary income,Trade in goods and services,Balances as a percentage of GDP1,2016
404,-1.7,K02000001,2017.0,Q1,D28M,GBP(millions),Total primary income,Trade in goods and services,Balances as a percentage of GDP1,2017
405,-2.6,K02000001,2017.0,Q2,D28M,GBP(millions),Total primary income,Trade in goods and services,Balances as a percentage of GDP1,2017
406,-2.2,K02000001,2017.0,Q3,D28M,GBP(millions),Total primary income,Trade in goods and services,Balances as a percentage of GDP1,2017
407,-1.2,K02000001,2015.0,,D28N,GBP(millions),Total secondary income,Trade in goods and services,Balances as a percentage of GDP1,2015
408,-1.1,K02000001,2016.0,,D28N,GBP(millions),Total secondary income,Trade in goods and services,Balances as a percentage of GDP1,2016
409,-0.9,K02000001,2015.0,Q3,D28N,GBP(millions),Total secondary income,Trade in goods and services,Balances as a percentage of GDP1,2015
410,-1.6,K02000001,2015.0,Q4,D28N,GBP(millions),Total secondary income,Trade in goods and services,Balances as a percentage of GDP1,2015
411,-1.1,K02000001,2016.0,Q1,D28N,GBP(millions),Total secondary income,Trade in goods and services,Balances as a percentage of GDP1,2016
412,-1.1,K02000001,2016.0,Q2,D28N,GBP(millions),Total secondary income,Trade in goods and services,Balances as a percentage of GDP1,2016
413,-1.2,K02000001,2016.0,Q3,D28N,GBP(millions),Total secondary income,Trade in goods and services,Balances as a percentage of GDP1,2016
414,-1.2,K02000001,2016.0,Q4,D28N,GBP(millions),Total secondary income,Trade in goods and services,Balances as a percentage of GDP1,2016
415,-0.9,K02000001,2017.0,Q1,D28N,GBP(millions),Total secondary income,Trade in goods and services,Balances as a percentage of GDP1,2017
416,-1.3,K02000001,2017.0,Q2,D28N,GBP(millions),Total secondary income,Trade in goods and services,Balances as a percentage of GDP1,2017
417,-1.1,K02000001,2017.0,Q3,D28N,GBP(millions),Total secondary income,Trade in goods and services,Balances as a percentage of GDP1,2017
418,-5.2,K02000001,2015.0,,AA6H,GBP(millions),None,Current balance as percentage of GDP,Balances as a percentage of GDP1,2015
419,-5.8,K02000001,2016.0,,AA6H,GBP(millions),None,Current balance as percentage of GDP,Balances as a percentage of GDP1,2016
420,-4.3,K02000001,2015.0,Q3,AA6H,GBP(millions),None,Current balance as percentage of GDP,Balances as a percentage of GDP1,2015
421,-7.1,K02000001,2015.0,Q4,AA6H,GBP(millions),None,Current balance as percentage of GDP,Balances as a percentage of GDP1,2015
422,-6.2,K02000001,2016.0,Q1,AA6H,GBP(millions),None,Current balance as percentage of GDP,Balances as a percentage of GDP1,2016
423,-5.6,K02000001,2016.0,Q2,AA6H,GBP(millions),None,Current balance as percentage of GDP,Balances as a percentage of GDP1,2016
424,-6.8,K02000001,2016.0,Q3,AA6H,GBP(millions),None,Current balance as percentage of GDP,Balances as a percentage of GDP1,2016
425,-4.6,K02000001,2016.0,Q4,AA6H,GBP(millions),None,Current balance as percentage of GDP,Balances as a percentage of GDP1,2016
426,-4.3,K02000001,2017.0,Q1,AA6H,GBP(millions),None,Current balance as percentage of GDP,Balances as a percentage of GDP1,2017
427,-5.1,K02000001,2017.0,Q2,AA6H,GBP(millions),None,Current balance as percentage of GDP,Balances as a percentage of GDP1,2017
428,-4.5,K02000001,2017.0,Q3,AA6H,GBP(millions),None,Current balance as percentage of GDP,Balances as a percentage of GDP1,2017

In [27]:
print(len(new_table))
new_table['TIME'] = new_table['TIME'].map(str) + new_table['Quarter']

429

In [28]:
print(len(new_table))
new_table

429

,OBS,GEOG,Year,Quarter,Code,Currency,Type of Services,Services,Account Transactions,TIME
0,288770.0,K02000001,2015.0,,BOKG,GBP(millions),Exports of goods,Exports of goods and services,Credits,2015
1,302067.0,K02000001,2016.0,,BOKG,GBP(millions),Exports of goods,Exports of goods and services,Credits,2016
2,71012.0,K02000001,2015.0,Q3,BOKG,GBP(millions),Exports of goods,Exports of goods and services,Credits,2015 Q3
3,71109.0,K02000001,2015.0,Q4,BOKG,GBP(millions),Exports of goods,Exports of goods and services,Credits,2015 Q4
4,69916.0,K02000001,2016.0,Q1,BOKG,GBP(millions),Exports of goods,Exports of goods and services,Credits,2016 Q1
5,74991.0,K02000001,2016.0,Q2,BOKG,GBP(millions),Exports of goods,Exports of goods and services,Credits,2016 Q2
6,74951.0,K02000001,2016.0,Q3,BOKG,GBP(millions),Exports of goods,Exports of goods and services,Credits,2016 Q3
7,82209.0,K02000001,2016.0,Q4,BOKG,GBP(millions),Exports of goods,Exports of goods and services,Credits,2016 Q4
8,83512.0,K02000001,2017.0,Q1,BOKG,GBP(millions),Exports of goods,Exports of goods and services,Credits,2017 Q1
9,86114.0,K02000001,2017.0,Q2,BOKG,GBP(millions),Exports of goods,Exports of goods and services,Credits,2017 Q2
10,86841.0,K02000001,2017.0,Q3,BOKG,GBP(millions),Exports of goods,Exports of goods and services,Credits,2017 Q3
11,228391.0,K02000001,2015.0,,IKBB,GBP(millions),Exports of services,Exports of goods and services,Credits,2015
12,252671.0,K02000001,2016.0,,IKBB,GBP(millions),Exports of services,Exports of goods and services,Credits,2016
13,56255.0,K02000001,2015.0,Q3,IKBB,GBP(millions),Exports of services,Exports of goods and services,Credits,2015 Q3
14,58442.0,K02000001,2015.0,Q4,IKBB,GBP(millions),Exports of services,Exports of goods and services,Credits,2015 Q4
15,60042.0,K02000001,2016.0,Q1,IKBB,GBP(millions),Exports of services,Exports of goods and services,Credits,2016 Q1
16,61808.0,K02000001,2016.0,Q2,IKBB,GBP(millions),Exports of services,Exports of goods and services,Credits,2016 Q2
17,63653.0,K02000001,2016.0,Q3,IKBB,GBP(millions),Exports of services,Exports of goods and services,Credits,2016 Q3
18,67168.0,K02000001,2016.0,Q4,IKBB,GBP(millions),Exports of services,Exports of goods and services,Credits,2016 Q4
19,68127.0,K02000001,2017.0,Q1,IKBB,GBP(millions),Exports of services,Exports of goods and services,Credits,2017 Q1
20,68769.0,K02000001,2017.0,Q2,IKBB,GBP(millions),Exports of services,Exports of goods and services,Credits,2017 Q2
21,69985.0,K02000001,2017.0,Q3,IKBB,GBP(millions),Exports of services,Exports of goods and services,Credits,2017 Q3
22,517161.0,K02000001,2015.0,,IKBH,GBP(millions),Total exports of goods and services,Exports of goods and services,Credits,2015
23,554738.0,K02000001,2016.0,,IKBH,GBP(millions),Total exports of goods and services,Exports of goods and services,Credits,2016
24,127267.0,K02000001,2015.0,Q3,IKBH,GBP(millions),Total exports of goods and services,Exports of goods and services,Credits,2015 Q3
25,129551.0,K02000001,2015.0,Q4,IKBH,GBP(millions),Total exports of goods and services,Exports of goods and services,Credits,2015 Q4
26,129958.0,K02000001,2016.0,Q1,IKBH,GBP(millions),Total exports of goods and services,Exports of goods and services,Credits,2016 Q1
27,136799.0,K02000001,2016.0,Q2,IKBH,GBP(millions),Total exports of goods and services,Exports of goods and services,Credits,2016 Q2
28,138604.0,K02000001,2016.0,Q3,IKBH,GBP(millions),Total exports of goods and services,Exports of goods and services,Credits,2016 Q3
29,149377.0,K02000001,2016.0,Q4,IKBH,GBP(millions),Total exports of goods and services,Exports of goods and services,Credits,2016 Q4
...,...,...,...,...,...,...,...,...,...,...
399,-3.8,K02000001,2015.0,Q4,D28M,GBP(millions),Total primary income,Trade in goods and services,Balances as a percentage of GDP1,2015 Q4
400,-3.1,K02000001,2016.0,Q1,D28M,GBP(millions),Total primary income,Trade in goods and services,Balances as a percentage of GDP1,2016 Q1
401,-2.9,K02000001,2016.0,Q2,D28M,GBP(millions),Total primary income,Trade in goods and services,Balances as a percentage of GDP1,2016 Q2
402,-2.2,K02000001,2016.0,Q3,D28M,GBP(millions),Total primary income,Trade in goods and services,Balances as a percentage of GDP1,2016 Q3
403,-2.0,K02000001,2016.0,Q4,D28M,GBP(millions),Total primary income,Trade in goods and services,Balances as a percentage of GDP1,2016 Q4
404,-1.7,K02000001,2017.0,Q1,D28M,GBP(millions),Total primary income,Trade in goods and services,Balances as a percentage of GDP1,2017 Q1
405,-2.6,K02000001,2017.0,Q2,D28M,GBP(millions),Total primary income,Trade in goods and services,Balances as a percentage of GDP1,2017 Q2
406,-2.2,K02000001,2017.0,Q3,D28M,GBP(millions),Total primary income,Trade in goods and services,Balances as a percentage of GDP1,2017 Q3
407,-1.2,K02000001,2015.0,,D28N,GBP(millions),Total secondary income,Trade in goods and services,Balances as a percentage of GDP1,2015
408,-1.1,K02000001,2016.0,,D28N,GBP(millions),Total secondary income,Trade in goods and services,Balances as a percentage of GDP1,2016
409,-0.9,K02000001,2015.0,Q3,D28N,GBP(millions),Total secondary income,Trade in goods and services,Balances as a percentage of GDP1,2015 Q3
410,-1.6,K02000001,2015.0,Q4,D28N,GBP(millions),Total secondary income,Trade in goods and services,Balances as a percentage of GDP1,2015 Q4
411,-1.1,K02000001,2016.0,Q1,D28N,GBP(millions),Total secondary income,Trade in goods and services,Balances as a percentage of GDP1,2016 Q1
412,-1.1,K02000001,2016.0,Q2,D28N,GBP(millions),Total secondary income,Trade in goods and services,Balances as a percentage of GDP1,2016 Q2
413,-1.2,K02000001,2016.0,Q3,D28N,GBP(millions),Total secondary income,Trade in goods and services,Balances as a percentage of GDP1,2016 Q3
414,-1.2,K02000001,2016.0,Q4,D28N,GBP(millions),Total secondary income,Trade in goods and services,Balances as a percentage of GDP1,2016 Q4
415,-0.9,K02000001,2017.0,Q1,D28N,GBP(millions),Total secondary income,Trade in goods and services,Balances as a percentage of GDP1,2017 Q1
416,-1.3,K02000001,2017.0,Q2,D28N,GBP(millions),Total secondary income,Trade in goods and services,Balances as a percentage of GDP1,2017 Q2
417,-1.1,K02000001,2017.0,Q3,D28N,GBP(millions),Total secondary income,Trade in goods and services,Balances as a percentage of GDP1,2017 Q3
418,-5.2,K02000001,2015.0,,AA6H,GBP(millions),None,Current balance as percentage of GDP,Balances as a percentage of GDP1,2015
419,-5.8,K02000001,2016.0,,AA6H,GBP(millions),None,Current balance as percentage of GDP,Balances as a percentage of GDP1,2016
420,-4.3,K02000001,2015.0,Q3,AA6H,GBP(millions),None,Current balance as percentage of GDP,Balances as a percentage of GDP1,2015 Q3
421,-7.1,K02000001,2015.0,Q4,AA6H,GBP(millions),None,Current balance as percentage of GDP,Balances as a percentage of GDP1,2015 Q4
422,-6.2,K02000001,2016.0,Q1,AA6H,GBP(millions),None,Current balance as percentage of GDP,Balances as a percentage of GDP1,2016 Q1
423,-5.6,K02000001,2016.0,Q2,AA6H,GBP(millions),None,Current balance as percentage of GDP,Balances as a percentage of GDP1,2016 Q2
424,-6.8,K02000001,2016.0,Q3,AA6H,GBP(millions),None,Current balance as percentage of GDP,Balances as a percentage of GDP1,2016 Q3
425,-4.6,K02000001,2016.0,Q4,AA6H,GBP(millions),None,Current balance as percentage of GDP,Balances as a percentage of GDP1,2016 Q4
426,-4.3,K02000001,2017.0,Q1,AA6H,GBP(millions),None,Current balance as percentage of GDP,Balances as a percentage of GDP1,2017 Q1
427,-5.1,K02000001,2017.0,Q2,AA6H,GBP(millions),None,Current balance as percentage of GDP,Balances as a percentage of GDP1,2017 Q2
428,-4.5,K02000001,2017.0,Q3,AA6H,GBP(millions),None,Current balance as percentage of GDP,Balances as a percentage of GDP1,2017 Q3

In [29]:
new_table = new_table.drop('Year', axis=1)
new_table = new_table.drop('Quarter', axis=1)

In [30]:
print(len(new_table))
new_table

429

,OBS,GEOG,Code,Currency,Type of Services,Services,Account Transactions,TIME
0,288770.0,K02000001,BOKG,GBP(millions),Exports of goods,Exports of goods and services,Credits,2015
1,302067.0,K02000001,BOKG,GBP(millions),Exports of goods,Exports of goods and services,Credits,2016
2,71012.0,K02000001,BOKG,GBP(millions),Exports of goods,Exports of goods and services,Credits,2015 Q3
3,71109.0,K02000001,BOKG,GBP(millions),Exports of goods,Exports of goods and services,Credits,2015 Q4
4,69916.0,K02000001,BOKG,GBP(millions),Exports of goods,Exports of goods and services,Credits,2016 Q1
5,74991.0,K02000001,BOKG,GBP(millions),Exports of goods,Exports of goods and services,Credits,2016 Q2
6,74951.0,K02000001,BOKG,GBP(millions),Exports of goods,Exports of goods and services,Credits,2016 Q3
7,82209.0,K02000001,BOKG,GBP(millions),Exports of goods,Exports of goods and services,Credits,2016 Q4
8,83512.0,K02000001,BOKG,GBP(millions),Exports of goods,Exports of goods and services,Credits,2017 Q1
9,86114.0,K02000001,BOKG,GBP(millions),Exports of goods,Exports of goods and services,Credits,2017 Q2
10,86841.0,K02000001,BOKG,GBP(millions),Exports of goods,Exports of goods and services,Credits,2017 Q3
11,228391.0,K02000001,IKBB,GBP(millions),Exports of services,Exports of goods and services,Credits,2015
12,252671.0,K02000001,IKBB,GBP(millions),Exports of services,Exports of goods and services,Credits,2016
13,56255.0,K02000001,IKBB,GBP(millions),Exports of services,Exports of goods and services,Credits,2015 Q3
14,58442.0,K02000001,IKBB,GBP(millions),Exports of services,Exports of goods and services,Credits,2015 Q4
15,60042.0,K02000001,IKBB,GBP(millions),Exports of services,Exports of goods and services,Credits,2016 Q1
16,61808.0,K02000001,IKBB,GBP(millions),Exports of services,Exports of goods and services,Credits,2016 Q2
17,63653.0,K02000001,IKBB,GBP(millions),Exports of services,Exports of goods and services,Credits,2016 Q3
18,67168.0,K02000001,IKBB,GBP(millions),Exports of services,Exports of goods and services,Credits,2016 Q4
19,68127.0,K02000001,IKBB,GBP(millions),Exports of services,Exports of goods and services,Credits,2017 Q1
20,68769.0,K02000001,IKBB,GBP(millions),Exports of services,Exports of goods and services,Credits,2017 Q2
21,69985.0,K02000001,IKBB,GBP(millions),Exports of services,Exports of goods and services,Credits,2017 Q3
22,517161.0,K02000001,IKBH,GBP(millions),Total exports of goods and services,Exports of goods and services,Credits,2015
23,554738.0,K02000001,IKBH,GBP(millions),Total exports of goods and services,Exports of goods and services,Credits,2016
24,127267.0,K02000001,IKBH,GBP(millions),Total exports of goods and services,Exports of goods and services,Credits,2015 Q3
25,129551.0,K02000001,IKBH,GBP(millions),Total exports of goods and services,Exports of goods and services,Credits,2015 Q4
26,129958.0,K02000001,IKBH,GBP(millions),Total exports of goods and services,Exports of goods and services,Credits,2016 Q1
27,136799.0,K02000001,IKBH,GBP(millions),Total exports of goods and services,Exports of goods and services,Credits,2016 Q2
28,138604.0,K02000001,IKBH,GBP(millions),Total exports of goods and services,Exports of goods and services,Credits,2016 Q3
29,149377.0,K02000001,IKBH,GBP(millions),Total exports of goods and services,Exports of goods and services,Credits,2016 Q4
...,...,...,...,...,...,...,...,...
399,-3.8,K02000001,D28M,GBP(millions),Total primary income,Trade in goods and services,Balances as a percentage of GDP1,2015 Q4
400,-3.1,K02000001,D28M,GBP(millions),Total primary income,Trade in goods and services,Balances as a percentage of GDP1,2016 Q1
401,-2.9,K02000001,D28M,GBP(millions),Total primary income,Trade in goods and services,Balances as a percentage of GDP1,2016 Q2
402,-2.2,K02000001,D28M,GBP(millions),Total primary income,Trade in goods and services,Balances as a percentage of GDP1,2016 Q3
403,-2.0,K02000001,D28M,GBP(millions),Total primary income,Trade in goods and services,Balances as a percentage of GDP1,2016 Q4
404,-1.7,K02000001,D28M,GBP(millions),Total primary income,Trade in goods and services,Balances as a percentage of GDP1,2017 Q1
405,-2.6,K02000001,D28M,GBP(millions),Total primary income,Trade in goods and services,Balances as a percentage of GDP1,2017 Q2
406,-2.2,K02000001,D28M,GBP(millions),Total primary income,Trade in goods and services,Balances as a percentage of GDP1,2017 Q3
407,-1.2,K02000001,D28N,GBP(millions),Total secondary income,Trade in goods and services,Balances as a percentage of GDP1,2015
408,-1.1,K02000001,D28N,GBP(millions),Total secondary income,Trade in goods and services,Balances as a percentage of GDP1,2016
409,-0.9,K02000001,D28N,GBP(millions),Total secondary income,Trade in goods and services,Balances as a percentage of GDP1,2015 Q3
410,-1.6,K02000001,D28N,GBP(millions),Total secondary income,Trade in goods and services,Balances as a percentage of GDP1,2015 Q4
411,-1.1,K02000001,D28N,GBP(millions),Total secondary income,Trade in goods and services,Balances as a percentage of GDP1,2016 Q1
412,-1.1,K02000001,D28N,GBP(millions),Total secondary income,Trade in goods and services,Balances as a percentage of GDP1,2016 Q2
413,-1.2,K02000001,D28N,GBP(millions),Total secondary income,Trade in goods and services,Balances as a percentage of GDP1,2016 Q3
414,-1.2,K02000001,D28N,GBP(millions),Total secondary income,Trade in goods and services,Balances as a percentage of GDP1,2016 Q4
415,-0.9,K02000001,D28N,GBP(millions),Total secondary income,Trade in goods and services,Balances as a percentage of GDP1,2017 Q1
416,-1.3,K02000001,D28N,GBP(millions),Total secondary income,Trade in goods and services,Balances as a percentage of GDP1,2017 Q2
417,-1.1,K02000001,D28N,GBP(millions),Total secondary income,Trade in goods and services,Balances as a percentage of GDP1,2017 Q3
418,-5.2,K02000001,AA6H,GBP(millions),None,Current balance as percentage of GDP,Balances as a percentage of GDP1,2015
419,-5.8,K02000001,AA6H,GBP(millions),None,Current balance as percentage of GDP,Balances as a percentage of GDP1,2016
420,-4.3,K02000001,AA6H,GBP(millions),None,Current balance as percentage of GDP,Balances as a percentage of GDP1,2015 Q3
421,-7.1,K02000001,AA6H,GBP(millions),None,Current balance as percentage of GDP,Balances as a percentage of GDP1,2015 Q4
422,-6.2,K02000001,AA6H,GBP(millions),None,Current balance as percentage of GDP,Balances as a percentage of GDP1,2016 Q1
423,-5.6,K02000001,AA6H,GBP(millions),None,Current balance as percentage of GDP,Balances as a percentage of GDP1,2016 Q2
424,-6.8,K02000001,AA6H,GBP(millions),None,Current balance as percentage of GDP,Balances as a percentage of GDP1,2016 Q3
425,-4.6,K02000001,AA6H,GBP(millions),None,Current balance as percentage of GDP,Balances as a percentage of GDP1,2016 Q4
426,-4.3,K02000001,AA6H,GBP(millions),None,Current balance as percentage of GDP,Balances as a percentage of GDP1,2017 Q1
427,-5.1,K02000001,AA6H,GBP(millions),None,Current balance as percentage of GDP,Balances as a percentage of GDP1,2017 Q2
428,-4.5,K02000001,AA6H,GBP(millions),None,Current balance as percentage of GDP,Balances as a percentage of GDP1,2017 Q3

In [31]:
new_table['Account Transactions'] = new_table['Account Transactions'].map(lambda x: x.rstrip('1'))

In [32]:
new_table.tail(5)

,OBS,GEOG,Code,Currency,Type of Services,Services,Account Transactions,TIME
424,-6.8,K02000001,AA6H,GBP(millions),None,Current balance as percentage of GDP,Balances as a percentage of GDP,2016 Q3
425,-4.6,K02000001,AA6H,GBP(millions),None,Current balance as percentage of GDP,Balances as a percentage of GDP,2016 Q4
426,-4.3,K02000001,AA6H,GBP(millions),None,Current balance as percentage of GDP,Balances as a percentage of GDP,2017 Q1
427,-5.1,K02000001,AA6H,GBP(millions),None,Current balance as percentage of GDP,Balances as a percentage of GDP,2017 Q2
428,-4.5,K02000001,AA6H,GBP(millions),None,Current balance as percentage of GDP,Balances as a percentage of GDP,2017 Q3

In [34]:

new_table.fillna('', inplace=True)

writetechnicalCSV('balanceofpayments2017q3tabB.csv', new_table)

writing 1 conversion segments into C:\Users\vamsi\balanceofpayments2017q3tabB.csv
pdconversionwrite segment size 429